[tool.poetry]
name = "moderator-packeges"
version = "0.1.0"
description = "Dependencies for moderator bot"
authors = ["serafimium"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12.7"
aiofiles = "24.1.0"
aiogram = "3.13.1"
aiohappyeyeballs = "2.4.3"
aiohttp = "3.10.10"
aiosignal = "1.3.1"
alembic = "1.13.3"
annotated-types = "0.7.0"
asyncpg = "0.30.0"
attrs = "24.2.0"
blis = "1.0.1"
cachetools = "5.5.0"
catalogue = "2.0.10"
certifi = "2024.8.30"
charset-normalizer = "3.4.0"
click = "8.1.7"
cloudpathlib = "0.20.0"
colorama = "0.4.6"
confection = "0.1.5"
cymem = "2.0.8"
DAWG-Python = "0.7.2"
frozenlist = "1.4.1"
greenlet = "3.1.1"
idna = "3.10"
isort = "5.13.2"
Jinja2 = "3.1.4"
langcodes = "3.4.1"
language_data = "1.2.0"
magic-filter = "1.0.12"
Mako = "1.3.6"
marisa-trie = "1.2.1"
markdown-it-py = "3.0.0"
MarkupSafe = "3.0.2"
mdurl = "0.1.2"
multidict = "6.1.0"
murmurhash = "1.0.10"
mypy = "1.12.1"
mypy-extensions = "1.0.0"
numpy = "2.0.2"
packaging = "24.1"
preshed = "3.0.9"
propcache = "0.2.0"
psycopg2 = "2.9.10"
pydantic = "2.9.2"
pydantic_core = "2.23.4"
Pygments = "2.18.0"
pymorphy3 = "2.0.2"
pymorphy3-dicts-ru = "2.4.417150.4580142"
python-dotenv = "1.0.1"
requests = "2.32.3"
rich = "13.9.3"
ruff = "0.7.0"
setuptools = "75.2.0"
shellingham = "1.5.4"
smart-open = "7.0.5"
spacy = "3.8.2"
spacy-legacy = "3.0.12"
spacy-loggers = "1.0.5"
SQLAlchemy = "2.0.36"
srsly = "2.4.8"
thinc = "8.3.2"
tqdm = "4.66.5"
typer = "0.12.5"
types-cachetools = "5.5.0.20240820"
typing_extensions = "4.12.2"
tzdata = "2024.2"
urllib3 = "2.2.3"
wasabi = "1.1.3"
weasel = "0.4.1"
wrapt = "1.16.0"
yarl = "1.16.0"
redis = "5.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"